### ISSUE TITLE
Support a sparse data format for uploads (e.g. matrix market) [Feature request]

### ISSUE THREAD

**Issue by matanhofree** [broadinstitute/single_cell_portal#10]
I'd suggest supporting a sparse matrix format for expression data uploads. Any would be reasonable. Matrix market is used often due its adoption by 10x. This would save time (and probably space when uploading large datasets).

**Comment by TimothyTickle** [comment]
This is an awesome idea and on our list, I will work on increasing its priority. Thank you for the feed back :-) .

**Comment by bistline** [comment]
Implemented 10X sparse matrix supprt as part of release [0.4.0](https://github.com/broadinstitute/single_cell_portal_core/releases/tag/v0.4.0).  See `https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/output/matrices` for more information.
