### ISSUE TITLE
Entry with several datasets 

### ISSUE THREAD

**Issue by Sara-Jager** [broadinstitute/single_cell_portal#117]
Dear Single Cell Portal Team,

I am working on a meta analysis where I compare different single cell RNAseq data sets. As part of the manuscript I would like a browser based way for readers to explore the data in each individual data set. I really like the functionality in your "Explore" tab. 

Is it possible to make an entry in your database with several data sets for exploration? 

Thank you
Sara

**Comment by eweitz** [comment]
Hi Sara,

Yes, you can achieve that by creating a study with multiple cluster files and expression files.  For example studies that contain multiple datasets, see:

* ["Cell Atlas of Aqueous Humor Outflow Pathways in Eyes of Humans and Four Model Species Provides Insights into Glaucoma Pathogenesis" (SCP780)](https://singlecell.broadinstitute.org/single_cell/study/SCP780/cell-atlas-of-aqueous-humor-outflow-pathways-in-eyes-of-humans-and-four-model-species-provides-insights-into-glaucoma-pathogenesis)
* ["The human and mouse enteric nervous system at single cell resolution" (SCP1038)](https://singlecell.broadinstitute.org/single_cell/study/SCP1038/the-human-and-mouse-enteric-nervous-system-at-single-cell-resolution)

The [Single Cell Portal wiki](https://github.com/broadinstitute/single_cell_portal/wiki) describes how to create studies and annotations, what comprises our various file types, and how those tie into the interactive visualizations shown in the application.

If more information would help, please let me know!

Best regards,
Eric

**Comment by Sara-Jager** [comment]
Hi Eric,

That sounds great and thanks for the speedy response. 

I will go and explore the wiki page and the studies.

Best regards Sara

**Comment by eweitz** [comment]
Sounds good!  I'll close this issue for now.  

Feel free to re-open if needed, or contact us over at scp-support@broadinstitute.zendesk.com.
