### ISSUE TITLE
Uploading wiki pictures

### ISSUE THREAD

**Issue by knapii-developments** [broadinstitute/single_cell_portal#118]
<img width="1232" alt="accept_terms_of_service" src="https://user-images.githubusercontent.com/37722472/111474690-af8efc80-8702-11eb-881a-2fb22c6c3593.png">
<img width="1272" alt="add_study_description" src="https://user-images.githubusercontent.com/37722472/111474704-b3228380-8702-11eb-9890-1b69a0083d41.png">
<img width="1270" alt="click_add_study" src="https://user-images.githubusercontent.com/37722472/111474706-b3228380-8702-11eb-995e-98ac1bbf3d5e.png">
<img width="1228" alt="click_create" src="https://user-images.githubusercontent.com/37722472/111474710-b3bb1a00-8702-11eb-880f-f33e43ae1a37.png">
<img width="1290" alt="click_sign_in" src="https://user-images.githubusercontent.com/37722472/111474711-b453b080-8702-11eb-9ee9-40c983fb0237.png">
<img width="1250" alt="name_study" src="https://user-images.githubusercontent.com/37722472/111474714-b4ec4700-8702-11eb-9aab-b954f9f14ac5.png">
<img width="1246" alt="set_date_embargo" src="https://user-images.githubusercontent.com/37722472/111474715-b584dd80-8702-11eb-94a2-908b7aed25c4.png">
<img width="1259" alt="set_study_permissions" src="https://user-images.githubusercontent.com/37722472/111474716-b584dd80-8702-11eb-95bf-76393b313328.png">

<img width="1028" alt="Screen Shot 2021-03-10 at 10 19 55 AM" src="https://user-images.githubusercontent.com/37722472/110652328-451e0f80-818a-11eb-8ab4-1d16fb8eb9f8.png">
<img width="1142" alt="Screen Shot 2021-03-10 at 10 22 14 AM" src="https://user-images.githubusercontent.com/37722472/110653723-8236d180-818b-11eb-98ca-ebc50533831e.png">

Synch
<img width="1274" alt="Screen Shot 2021-03-18 at 9 42 46 AM" src="https://user-images.githubusercontent.com/37722472/111638944-2f839800-87d1-11eb-8b24-9a0aefd44021.png">
<img width="1231" alt="Screen Shot 2021-03-18 at 9 42 56 AM" src="https://user-images.githubusercontent.com/37722472/111638953-327e8880-87d1-11eb-82e6-bf5b48d713e3.png">
<img width="1273" alt="Screen Shot 2021-03-18 at 9 43 03 AM" src="https://user-images.githubusercontent.com/37722472/111638957-33171f00-87d1-11eb-9882-d79a762985c3.png">
<img width="1202" alt="Screen Shot 2021-03-18 at 9 43 10 AM" src="https://user-images.githubusercontent.com/37722472/111638959-33afb580-87d1-11eb-8826-085a976c6836.png">
<img width="1188" alt="Screen Shot 2021-03-18 at 9 43 19 AM" src="https://user-images.githubusercontent.com/37722472/111638964-33afb580-87d1-11eb-88b6-eba6fdfb9cdf.png">
<img width="1253" alt="Screen Shot 2021-03-18 at 9 43 25 AM" src="https://user-images.githubusercontent.com/37722472/111638965-34484c00-87d1-11eb-982c-6ff3bf83aadc.png">
<img width="1195" alt="Screen Shot 2021-03-18 at 9 43 33 AM" src="https://user-images.githubusercontent.com/37722472/111638966-34e0e280-87d1-11eb-9ef3-4279e44622c2.png">
<img width="1169" alt="Screen Shot 2021-03-18 at 9 43 40 AM" src="https://user-images.githubusercontent.com/37722472/111638969-34e0e280-87d1-11eb-9ae0-1eb77c3fedca.png">
<img width="1227" alt="Screen Shot 2021-03-18 at 9 43 50 AM" src="https://user-images.githubusercontent.com/37722472/111638970-34e0e280-87d1-11eb-88f8-f65db78964c4.png">
<img width="1222" alt="Screen Shot 2021-03-18 at 9 43 56 AM" src="https://user-images.githubusercontent.com/37722472/111638972-35797900-87d1-11eb-847f-50498318fbf2.png">
<img width="1272" alt="Screen Shot 2021-03-18 at 9 44 03 AM" src="https://user-images.githubusercontent.com/37722472/111638974-35797900-87d1-11eb-992e-86f130fd1421.png">
<img width="1122" alt="Screen Shot 2021-03-18 at 9 44 11 AM" src="https://user-images.githubusercontent.com/37722472/111638977-35797900-87d1-11eb-93bd-5fbc86148c42.png">
<img width="1279" alt="Screen Shot 2021-03-18 at 9 44 19 AM" src="https://user-images.githubusercontent.com/37722472/111638980-36120f80-87d1-11eb-9343-6ce5d423b90d.png">

<img width="867" alt="show_details copy" src="https://user-images.githubusercontent.com/37722472/111319584-8b68e800-863c-11eb-95c7-7f6c41b9940b.png">
<img width="915" alt="sharing_private_studies_confirm_user_added" src="https://user-images.githubusercontent.com/37722472/111319586-8c017e80-863c-11eb-97ef-2465f4adf8f6.png">
<img width="822" alt="sharing_private_studies_update_study" src="https://user-images.githubusercontent.com/37722472/111324961-9f631880-8641-11eb-8e12-785be8316de0.png">

<img width="716" alt="sharing_private_studies_share_study_button" src="https://user-images.githubusercontent.com/37722472/111319591-8c9a1500-863c-11eb-9e90-2837a3111a6f.png">
<img width="766" alt="edit_study copy" src="https://user-images.githubusercontent.com/37722472/111319592-8c9a1500-863c-11eb-98a7-89b7976eccfa.png">
<img width="1028" alt="my_studies_screenshot copy" src="https://user-images.githubusercontent.com/37722472/111319593-8c9a1500-863c-11eb-9ca2-3496fd483373.png">

Download Tab:
<img width="1292" alt="click_download_command" src="https://user-images.githubusercontent.com/37722472/111353398-a5fe8980-865b-11eb-9a7f-7ecdcc95c324.png">
<img width="1294" alt="click_download_tab" src="https://user-images.githubusercontent.com/37722472/111353423-ac8d0100-865b-11eb-998d-7a5354b767d8.png">
<img width="1296" alt="download_data" src="https://user-images.githubusercontent.com/37722472/111353427-adbe2e00-865b-11eb-9422-922aab071270.png">
<img width="1294" alt="get_download_command" src="https://user-images.githubusercontent.com/37722472/111353433-aeef5b00-865b-11eb-8118-0733c6ff9f01.png">
<img width="1292" alt="select_a_study" src="https://user-images.githubusercontent.com/37722472/111353437-af87f180-865b-11eb-9532-f73e39f62afc.png">

Upload wizard after study creation
<img width="1192" alt="click_upload_ Miscellaneous" src="https://user-images.githubusercontent.com/37722472/111481169-144d5580-8709-11eb-9739-bea102129027.png">
<img width="1293" alt="click_upload_and_save_cluster" src="https://user-images.githubusercontent.com/37722472/111481183-16afaf80-8709-11eb-9c73-22ae36b6fc66.png">
<img width="1164" alt="click_upload_and_save_sequence_files" src="https://user-images.githubusercontent.com/37722472/111481185-17484600-8709-11eb-975f-4550c1456d33.png">
<img width="1245" alt="complete_upload_process" src="https://user-images.githubusercontent.com/37722472/111481190-18797300-8709-11eb-9085-78b1d33f2222.png">
<img width="1200" alt="done" src="https://user-images.githubusercontent.com/37722472/111481193-19120980-8709-11eb-9c35-8188e8f4b03e.png">
<img width="1225" alt="miscellaneous_success_modal" src="https://user-images.githubusercontent.com/37722472/111481199-1a433680-8709-11eb-9f68-bef26566ed64.png">
<img width="1217" alt="upload_cluster" src="https://user-images.githubusercontent.com/37722472/111481200-1adbcd00-8709-11eb-8363-3aa56e21f9a6.png">
<img width="1255" alt="upload_cluster_modal" src="https://user-images.githubusercontent.com/37722472/111481210-1c0cfa00-8709-11eb-841c-b7202ae58af5.png">
<img width="1212" alt="upload_gene_expression_files" src="https://user-images.githubusercontent.com/37722472/111481213-1c0cfa00-8709-11eb-9393-6c5aed159978.png">
<img width="1227" alt="upload_gene_list" src="https://user-images.githubusercontent.com/37722472/111481219-1d3e2700-8709-11eb-89be-24d6fe32e7e3.png">
<img width="1147" alt="upload_metadata" src="https://user-images.githubusercontent.com/37722472/111481224-1d3e2700-8709-11eb-8153-4f41c10bd44a.png">
<img width="1219" alt="upload_miscellaneous" src="https://user-images.githubusercontent.com/37722472/111481226-1e6f5400-8709-11eb-9ad4-0919b8a77b7b.png">
<img width="1227" alt="upload_sequence_files" src="https://user-images.githubusercontent.com/37722472/111481227-1e6f5400-8709-11eb-8bed-02569c534f00.png">
<img width="1155" alt="upload_success_modal" src="https://user-images.githubusercontent.com/37722472/111481228-1f07ea80-8709-11eb-9abf-fae6fa3b0283.png">
<img width="1289" alt="uploading_modal_cluster" src="https://user-images.githubusercontent.com/37722472/111481229-1f07ea80-8709-11eb-8b48-f6933f459001.png">
<img width="1230" alt="upload_save_gene_file" src="https://user-images.githubusercontent.com/37722472/111486013-7e67f980-870d-11eb-857a-470e7c69058a.png">
<img width="1220" alt="upload_gene_file" src="https://user-images.githubusercontent.com/37722472/111486130-99d30480-870d-11eb-8fcb-fec23ebc6b73.png">

<img width="1238" alt="Screen Shot 2021-03-17 at 11 34 17 AM" src="https://user-images.githubusercontent.com/37722472/111495395-b4a97700-8715-11eb-8828-76ea25806e14.png">
<img width="1261" alt="Screen Shot 2021-03-17 at 11 34 24 AM" src="https://user-images.githubusercontent.com/37722472/111495409-b7a46780-8715-11eb-95f5-ac9d24275f6d.png">
<img width="1079" alt="Screen Shot 2021-03-17 at 11 34 34 AM" src="https://user-images.githubusercontent.com/37722472/111495410-b83cfe00-8715-11eb-9d0f-420e9ec209e5.png">
<img width="1238" alt="Screen Shot 2021-03-17 at 11 34 41 AM" src="https://user-images.githubusercontent.com/37722472/111495415-b83cfe00-8715-11eb-8581-9b8ca1cafa6b.png">
<img width="1208" alt="Screen Shot 2021-03-17 at 11 34 47 AM" src="https://user-images.githubusercontent.com/37722472/111495416-b8d59480-8715-11eb-9043-b640b2a85682.png">
<img width="1182" alt="Screen Shot 2021-03-17 at 11 34 53 AM" src="https://user-images.githubusercontent.com/37722472/111495417-b8d59480-8715-11eb-8701-a88e6fa0abe9.png">

**Comment by eweitz** [comment]
This was done over in #119, I believe.
