### ISSUE TITLE
download individual files using command line

### ISSUE THREAD

**Issue by hurleyLi** [broadinstitute/single_cell_portal#124]
Hello,
I tried to download individual files, but current behavior for downloading files when clicking the "blue download icon" is to open files directly on browser. Could you please let me know how to download the file on desktop or provide any command line to download individual files?
Thanks!
Hurley

**Comment by eweitz** [comment]
Hi @hurleyLi, thanks for using Single Cell Portal!  Here are two ways to download individual files from SCP to your desktop:

* Click link, then save raw file shown in web browser (e.g. via Command + S on macOS, Ctrl + S on Windows)
* Right-click link, then select "Save Link As..."

Does that help?

Also, just FYI, you can also get support by emailing scp-support@broadinstitute.zendesk.com if you wish.

**Comment by hurleyLi** [comment]
Thanks for the quick response! Yes "Save Link As..." works... 
I guess I meant to say how to use __command line__ to download the files, e.g. is there any curl or wget command I can use. I tried the command with the links I got from "Copy Link Address" (from that blue button) and the link with "GoogleAccessId=" from the browser when I click the blue button, but neither works. 
Thanks!

**Comment by eweitz** [comment]
Ah, I see.  Have you tried the "Bulk Download" button -- just above the top of the blue download buttons?

Bulk download gives you a `curl` command to download all files in the study.  That may well provide more data than you seek, but it's the most convenient way to get individual files by command line.

Those `curl` commands have a one-time access token that expires after 30 minutes, and downloads are limited to 0.5 TB per day, so they're tailored for users interacting with the GUI and not suitable for building into other software.  But if you're looking for a `curl` command to download individual files, they're the best option.  You can also bulk download search results from the home page with a similar (and slightly more flexible) `curl` command, but it has the same timeout, daily quota, and originated-via-GUI features.

If such `curl` commands wouldn't suit your needs, could you talk a bit more about your use case?

**Comment by hurleyLi** [comment]
What I really need is just a subset of files (most time), since I have limited space on cluster. I think the "Bulk Download" would work for me, I can download everything and delete the files that I don't need -- if that's the only easy option for downloading via command (is it?). 
Thanks!

**Comment by eweitz** [comment]
Great, yes, bulk downloading then deleting files you don't need sounds like it might be the fastest solution for you, for now.

If you'd be available to chat later about how this experience could be improved for use cases like yours, could you email us over at scp-support@broadinstitute.zendesk.com ?

**Comment by hurleyLi** [comment]
Thanks @eweitz 

> Great, yes, bulk downloading then deleting files you don't need sounds like it might be the fastest solution for you, for now.
> 
> If you'd be available to chat later about how this experience could be improved for use cases like yours, could you email us over at [scp-support@broadinstitute.zendesk.com](mailto:scp-support@broadinstitute.zendesk.com) ?

Will do. Thank you @eweitz !

**Comment by eweitz** [comment]
I appreciate that, @hurleyLi!  Thanks again for using Single Cell Portal.
