### ISSUE TITLE
Issue switching between cluster results on the same 

### ISSUE THREAD

**Issue by matanhofree** [broadinstitute/single_cell_portal#13]
Switching between cluster results does not seem to bring up cells not in the intersection of the two sets without a manual refresh.

**Comment by bistline** [comment]
Can you explain more what you're expecting to happen?  The cluster dropdown menu just loads whatever cells were defined in the specified cluster, and then colors them according to the selected annotation.

**Comment by matanhofree** [comment]
It looks like after switching to one view with fewer cells the only way to
switch back was a manual refresh. In my case one clustering result was a
subset of the other.
In other words, I have two clusterings one with ~4000 and another with a
subset with 3000 cells. If I switch to the 3000 view it does not change
back.

Best,
Matan

**Comment by bistline** [comment]
Can you tell me which study/clusters you're looking at so I can investigate?

**Comment by bistline** [comment]
strip whitespace from cluster & gene list names when parsing
