### ISSUE TITLE
Feature request: view mode without download access

### ISSUE THREAD

**Issue by matanhofree** [broadinstitute/single_cell_portal#14]
A useful collaboration tool would be a more limited view only mode. Basically limited someone for being able to download our data and easily share it with a 3rd party without our consent.

**Comment by matanhofree** [comment]
Any update on this feature request? It sounded like this was in the works.  

Best,
Matan

**Comment by bistline** [comment]
Apologies for the delay on this.  We're waiting for FireCloud to implement a permission model to support this.  Currently, if you have READER access to a study, you can also download data.  We have no way of restricting access to a user to be able to see the workspace/study but not download the data.

I'll talk to the FireCloud team and see what the status of this feature is.

**Comment by bistline** [comment]
We are moving ahead with this feature without direct permissions - the plan is to not allow FireCloud/GCS access at all and only provide access to parsed data through the portal.  No downloads or sharing will be permitted.  

This has been moved to the current sprint and will be scheduled for the following deployment window.
