### ISSUE TITLE
Incorrect cell clusters file causes the system to hang

### ISSUE THREAD

**Issue by allonw** [broadinstitute/single_cell_portal#2]
When uploading the attached file (I forgot that cluster and sub-clusters cannot have the same names when I produced it) the system hangs indefinitely instead of producing an error message.
[cellAssignments.txt](https://github.com/broadinstitute/single_cell_portal/files/421251/cellAssignments.txt)

**Comment by allonw** [comment]
Thinking of it, I think that you should allow clusters to have the same names as sub-clusters: currently there's no natural way to represent a main cluster that has no obvious division into sub-clusters.

**Comment by allonw** [comment]
Fixed the file (at least I think it's fixed now), system still hangs when I try to upload it
[cellAssignments.txt](https://github.com/broadinstitute/single_cell_portal/files/421464/cellAssignments.txt)

**Comment by bistline** [comment]
Looking at the file, the headers are incorrect - the first column should be CELL_NAME, not CELL_LABEL.  However, it should throw and error - I'll investigate why it's not doing that.

**Comment by bistline** [comment]
Refactored error handling and messages, fixed JS error that prevented modals from showing with messages
