### ISSUE TITLE
tSNE plot shows continuous but not discrete data

### ISSUE THREAD

**Issue by farrellja** [broadinstitute/single_cell_portal#21]
Hi Team!

I'm having an issue with one of my sets of cluster coordinates not displaying correctly. The affected study is: [https://portals.broadinstitute.org/single_cell/study/single-cell-reconstruction-of-developmental-trajectories-during-zebrafish-embryogenesis](https://portals.broadinstitute.org/single_cell/study/single-cell-reconstruction-of-developmental-trajectories-during-zebrafish-embryogenesis)

There are two cluster files (**URD Developmental Tree** and **tSNE - All Cells**). For **URD Developmental Tree**, everything displays as expected. For **tSNE - All Cells**, the points fail to display when colored by discrete annotations (i.e. **Stage** or **Lineage_Spinal_Cord**) but when plotting expression of a gene, it is normal. The points are there (the hover works fine), but I just can't see them. On my computer, this affects Safari, but not Chrome. I tried also another computer that had never visited the site and had the same issue in Safari, so I think it might be browser wide, though I am not sure.

I attach two screenshots - one showing the affected view (**tSNE - All Cells**) and the other showing an unaffected view (**URD Developmental Tree**).

<img width="800" alt="screen shot 2018-04-26 at 3 08 09 pm" src="https://user-images.githubusercontent.com/7209771/39326712-e2136f7c-4963-11e8-939e-6b6bbf877b13.png">

<img width="800" alt="screen shot 2018-04-26 at 3 09 25 pm" src="https://user-images.githubusercontent.com/7209771/39326704-dacb0d24-4963-11e8-8b62-c7bf296b7d31.png">

Thanks for your help!
Jeff

**Comment by bistline** [comment]
This is a bug that was just found in Plotly.js apparently: [#2457](https://github.com/plotly/plotly.js/issues/2457).  It was only opened about a week ago, so it doesn't appear they have a fix for it yet.  For now, I'd say just use Chrome.  Once they've fixed it, we'll do a release to bump up the Plotly.js version to include it.

**Comment by bistline** [comment]
Looks like Plotly will have a fix for this [soon](https://github.com/plotly/plotly.js/pull/2593), so once it's released we'll merge an update in and schedule it for deployment.

**Comment by farrellja** [comment]
Great! Thanks, Jon! People so far seem to enjoying browsing our data in the single-cell portal, and they're finding it useful. So, thanks for making this tool available!!!

**Comment by bistline** [comment]
This has been patched in [v1.37.1](https://github.com/plotly/plotly.js/releases/tag/v1.37.1), so we'll be doing a release tomorrow for this.

**Comment by farrellja** [comment]
I just checked, and it seems to be working properly now! Thanks so much, Jon!
