### ISSUE TITLE
Cannot access the website after logging with a gmail account.

### ISSUE THREAD

**Issue by CancerGenome** [broadinstitute/single_cell_portal#22]
I want to download some dataset from single cell portal. 
Will show the context before logging, however,  disappear after logging. 

Here is the log from the website:

"We're sorry, but something went wrong.
Please report an issue if this problem persists."

**Comment by bistline** [comment]
Thanks for reporting this - this is apparently a bug with a new feature we deployed yesterday.  It appears your account is not registered for FireCloud, and we are getting errors when trying to check group permissions.  It should skip this if you aren't registered with FireCloud yet.

I think this is a pretty easy fix, so let me see if I can patch it for you.

**Comment by bistline** [comment]
OK - can you try it now?  I was able to log in with an account that has no FireCloud profile yet.
