### ISSUE TITLE
"/" and "-" not allowed in CLUSTER names?

### ISSUE THREAD

**Issue by hypercompetent** [broadinstitute/single_cell_portal#3]
It looks like plotly/D3 may not like cluster names that have a "/" or "-" character in them.

I uploaded a cluster set that included "L2/3" in some of the CLUSTER names. With this in place, the plot for tsne coordinates wouldn't render, and the JavaScript error console reported this error:
"SyntaxError: unterminated regular expression literal"

on this line:
var Gluta_L2/3 = {
		x: [23.0070565915785, 20.3435385139271, 10.6567142980721, 20.0861135630354, 10.4934771719043, 23.1146356898364, 22.8574848155296, 21.3218517622283, 22.4250576465239, 26.3419645413995, 25.0499547109735, 23.0558178974129, 24.2806536638378, 20.0832056194245, 21.6816976998642, 24.37897571043, 23.1521946939786, 24.8878386755833, 20.4077845399647, 21.8042107002554, 20.2685103439855, 18.5389008583059, 24.5480853996053, 21.9227665514889, 24.7662030552778, 19.4416286768367, 24.4178783414773, 24.7597171679464, 21.4233441574537, 24.5187020407513, 24.1349531310971, 26.0711354168533, 19.9530629185698, 19.8106468887377, 20.7414626205473, 19.7888515980719, 26.4322418302953, 21.3268354323789, 10.0917135197877, 9.6242828027858, 21.0050297942425, 25.6242264941051, 25.574939673233, 21.0499694589572, 26.0983270776546, 23.6271862226419, 19.9242189060272, 25.3657930541201, 25.4002558016465, 25.8568382790818, 10.9693191486601, 22.1994199808977, 9.88507098332818, 23.1037315859001, 25.3194491884043, 24.6189864173978, 24.2894886380146, 26.0805073345582, 24.4342784591951, 22.0481164684767, 19.9905233375605, 18.3416566013275, 20.0739700776901, 26.6892406887497, 25.0199446965639, 24.3176597988006, 24.3312199920918, 26.1775625270968, 25.0023175866302, 9.99801848253464, 20.1925388026716, 24.6229325755108, 21.1162264172455, 25.9031153726463, 11.6553795055581, 20.6610705571753, 24.9981749588173, 24.0967329820237, 21.8590620442522, 20.1345408656556, 24.7441389564347, 23.6965086929425, 23.6459101557375, 24.5449234290759, 23.6410794410479, 24.8635629403444, 22.8509312884044, 21.1807518614606, 25.7326418893053, 21.0111406714256, 22.7953672692683, 14.4980966548631],

When I submitted a file with L2-3 instead of L2/3, I again got no plot, and a similar error in the error console.

Finally, switching to Gluta_L2_3 worked fine.

I'm not sure this is really a bug in the code, but it may be good to say what characters aren't allowed in the CLUSTER columns on the upload page. I guess this may include characters that JavaScript will try to interpret.

Cheers,
Lucas Gray, Allen Institute for Brain Science

**Comment by TimothyTickle** [comment]
Hello Lucas,

It is best to restrict gene names, cluster names, and other ids to alphanumeric characters (also allowing underscores). Although as you mentioned this is not a bug, it certainly is a place for us to improve our communication. I have updated the wiki under file formats. Please let me know if the wiki does not communicate this. I will also ask our developer to take a look at the wizard's text.

Thank you for the feedback,

Tim

**Comment by TimothyTickle** [comment]
Hello Lucas,

We updated the system so that most characters can be used to give you more flexibility; the only exception would be quotes. Thank you for helping us increase the usability of the portal.

Cordially,

Tim
