### ISSUE TITLE
REST API?

### ISSUE THREAD

**Issue by Bohdan-Khomtchouk** [broadinstitute/single_cell_portal#35]
Are there any plans or timeline to develop a REST API for Single Cell Portal?

**Comment by vickylihorst** [comment]
Hi Bohdan, thanks for reaching out. We are actively developing the REST API for SCP; are there any specific features you are looking for?

**Comment by Bohdan-Khomtchouk** [comment]
Hi @vickylihorst thanks for your note.  Happy to see that your team has developed a REST API.
