### ISSUE TITLE
Cannot add a study

### ISSUE THREAD

**Issue by slowkow** [broadinstitute/single_cell_portal#36]
Steps:

1. I logged in with my Broad account.

2. I clicked "Add a Study".

3. I got `We're sorry, but something went wrong.`

![single cell portal - google chrome 2018-09-26_16-22-29](https://user-images.githubusercontent.com/209714/46107345-1b82f080-c1a9-11e8-9db4-38cc791720fa.png)

**Comment by vickylihorst** [comment]
Thanks for reporting the issue @slowkow. I just tried to add a study just now, and it went fine for me. I wonder if it's a browser caching issue. Could you clear out your cache and try again?

**Comment by bistline** [comment]
I'm looking in the logs, and there appears to be an issue with checking FireCloud registration status.  I'll update when I know more.

**Comment by bistline** [comment]
There does appear to be a bug now with checking whether or not a user is registered for FireCloud.  The response from the API has changed, and we were being to strict in checking the message.  I've implemented a patch for this locally and verified that it works.

This fix will go out with tomorrow's deployment at around lunchtime, @slowkow.  If you don't want to wait until then, you can sidestep the problem by going to portal.firecloud.org and signing up with your Broad email address.

**Comment by slowkow** [comment]
I could not create an account on FireCloud in Chrome or Firefox, maybe due to ad blockers. When I tried to login with the Google button, it did not respond at all. 

It worked in Safari, so I could see a registration page and provided my information.

After I registered on FireCloud, the error message on the Single Cell Portal went away, and it looks like I have access to add a study.

Thanks for the tip!

Is it possible to add public data to the portal for free? Or is the Broad Single Cell Portal only for paying customers?

**Comment by bistline** [comment]
@slowkow Glad to hear that registering finally worked for you.  I did just release a patch that fixed the problem for other users.  Thanks for reporting that.

In regards to data, you can definitely add data and make it publicly available for free, provided it is not restricted in any way (we do not allow human sequence data currently).  However, you will not be able to run any computes in your study either through the Single Cell Portal or FireCloud in that workspace.  Usually, though, this is not a concern for regular users, so it shouldn't impact you at all if you only want to make data available for public download.  Users still need to sign in to download, and we enforce a daily quota on downloads (per user), but other than that there is no restriction on adding data.
