### ISSUE TITLE
Cannot open any studies

### ISSUE THREAD

**Issue by nkogan** [broadinstitute/single_cell_portal#42]
All that's displayed is a "We're sorry, but something went wrong." error message upon attempting to download any study data (as well as a "502 Bad Gateway" message)

**Comment by bistline** [comment]
@nkogan there are currently some networking issues with some of our external dependencies that are causing intermittent issues.  These will hopefully be resolved soon.

**Comment by nkogan** [comment]
@bistline is there any estimate of when things will be back up? Thank you!

**Comment by bistline** [comment]
@nkogan things look like they have quieted down.  Can you try logging out and back in again to see if you are still having issues?

**Comment by nkogan** [comment]
@bistline seems to be working now! Thank you
