### ISSUE TITLE
Citation information

### ISSUE THREAD

**Issue by Bohdan-Khomtchouk** [broadinstitute/single_cell_portal#46]
I would like to cite your excellent portal.  What citation information should I use to refer to Single Cell Portal?

**Comment by Bohdan-Khomtchouk** [comment]
I just want to cite the portal in general, not any specific study.

**Comment by vickylihorst** [comment]
Hi @Bohdan-Khomtchouk, for now, you can just use our home page URL (https://portals.broadinstitute.org/single_cell). We plan to move SCP out of beta and release an application note next year, so by then people can cite the app note.
