### ISSUE TITLE
Studies loading very slowly

### ISSUE THREAD

**Issue by gurmank** [broadinstitute/single_cell_portal#48]
Hi,
I am having trouble with the portal for the last 2-3 days. My studies are taking a very long time to load. I haven't had this loading issue before. 
Thanks

**Comment by bistline** [comment]
Could you please let us know which study in particular you're having issues with?  I'm not seeing a slowdown on any public studies right now.

**Comment by gurmank** [comment]
All my studies are private, and it seems to be the same for all of them. I can get to 'My studies' page fine and then any study i click on - it takes a long time to open it. Once the study is loaded - i can explore it okay.

**Comment by bistline** [comment]
Can you give me the name of one of those studies?  That way I can look at the logs and see what the slowdown is.

**Comment by bistline** [comment]
Thanks - I'm seeing the issue now, and it's related to some recent changes we made to how we handle retries on errors (we have staggered backoffs, which is what you're seeing now), and also something that's wrong with the permissions on the FireCloud workspace that is backing the study.  It's returning an error when we try to load it, and it's causing the retry loop that is taking a long time to load your study as a result.

I'll work with the engineers on the FireCloud side to get this resolved as soon as we can.  I apologize for the inconvenience in the meantime.

**Comment by gurmank** [comment]
Thanks for looking into it.

**Comment by bistline** [comment]
So the FireCloud team has identified the issue and they're working on fixing it right now.  It looks pretty straightforward, so this should hopefully be resolved soon - I'll let you know once it's fixed.  Thanks again for you patience.

**Comment by bistline** [comment]
The issue has been fixed, and I verified that I could pull up PE_10x_NK_08072018 without any delays.  The FireCloud workspace sharing tab for this study also is loading properly now.

We will also be addressing this issue you experienced with the delay in loading in more depth in an upcoming release.  Thanks for bringing this to our attention.

**Comment by gurmank** [comment]
Thank you very much for resolving this issue.
