### ISSUE TITLE
Extracting study metadata

### ISSUE THREAD

**Issue by Alanocallaghan** [broadinstitute/single_cell_portal#52]
I would like to gather metadata across all (public) studies on the portal (primarily date, author and number of cells/genes). Is there a way to accomplish this using an API or through a web browser?

Thanks for the great resource.

**Comment by eweitz** [comment]
@Alanocallaghan, yes, you should be able to do this with the new [Python bindings](https://github.com/broadinstitute/single_cell_portal/blob/master/scripts/scp_api.py) for Single Cell Portal,  which wrap the [SCP REST API](https://portals.broadinstitute.org/single_cell/api/swagger_docs/v1).  Below is example code to get you up and running.

First, [set up](https://github.com/broadinstitute/single_cell_portal#convenience-scripts) the scripts from this repo on your machine.  Then download the attached [`extract_public_study_metadata.py.txt`](https://github.com/broadinstitute/single_cell_portal/files/2819432/extract_public_study_metadata.py.txt) file, copy it to `single_cell_portal/scripts`, change to that directory, truncate ".txt" from the file name, and run it like so:

```
(env) scripts eweitz$ python3 extract_public_study_metadata.py --token `gcloud auth print-access-token`
```

(The example lacks study author; I'll chat with the team about making it available in the REST API.)

We'd be interested to hear your feedback on these Python bindings and the REST API!

**Comment by Alanocallaghan** [comment]
Fantastic, thanks!

On 31 Jan 2019 11:31 pm, Eric Weitz <notifications@github.com> wrote:

@Alanocallaghan<https://github.com/Alanocallaghan>, yes, you should be able to do this with the new Python bindings<https://github.com/broadinstitute/single_cell_portal/blob/master/scripts/scp_api.py> for Single Cell Portal, which wrap the SCP REST API<https://portals.broadinstitute.org/single_cell/api/swagger_docs/v1>. Below is example code to get you up and running.

First, set up<https://github.com/broadinstitute/single_cell_portal#convenience-scripts> the scripts from this repo on your machine. Then download the attached extract_public_study_metadata.py.txt<https://github.com/broadinstitute/single_cell_portal/files/2819432/extract_public_study_metadata.py.txt> file, copy it to single_cell_portal/scripts, change to that directory, truncate ".txt" from the file name, and run it like so:

(env) scripts eweitz$ python3 extract_public_study_metadata.py --token `gcloud auth print-access-token`


(The example lacks study author; I'll chat with the team about making it available in the REST API.)

We'd be interested to hear your feedback on these Python bindings and the REST API!

**Comment by Alanocallaghan** [comment]
@eweitz thanks for the script! API seems to make sense after having a very quick look. Unfortunately the API at the moment doesn't allow polling of general portal information, only that which relates directly to the logged in user. The [API docs](https://portals.broadinstitute.org/single_cell/api/swagger_docs/v1#!/Studies/studies_path) indicate as much: 
>Implementation Notes
Returns all Studies editable by the current user

It would be nice to be able to get general information about all (public) studies. Thanks again!

**Comment by eweitz** [comment]
Glad to help!

You're right about the [`/studies`](https://portals.broadinstitute.org/single_cell/api/swagger_docs/v1#!/Studies/studies_path) endpoint, but the script actually filters out non-public studies in its [`print_summaries`](https://gist.github.com/eweitz/8b7b240b57e282e7c354eb37abecb938#file-extract_scp_study_metadata-py-L14) function.  I [added a few lines](https://gist.github.com/eweitz/8b7b240b57e282e7c354eb37abecb938#file-extract_scp_study_metadata-py-L47) that print the number of public studies, and they output "68", matching the number I see in the banner atop https://portals.broadinstitute.org/single_cell when not signed in.

[See this gist](https://gist.github.com/eweitz/8b7b240b57e282e7c354eb37abecb938) for the updated script.

**Comment by Alanocallaghan** [comment]
I get an empty response after authenticating with the same google account I used for my SCP account (which has no studies). There was already code in the script to filter non-public studies; I simply get no information regardless of filtering.

To be clear, when I run
```python
studies = manager.do_get(api_base_endpoint + 'studies')
```
I get
```
DO GET
https://portals.broadinstitute.org/single_cell/api/v1/studies
<Response [200]>
```

**Comment by eweitz** [comment]
It looks like you omitted the last part; try:

```python
studies = manager.do_get(api_base_endpoint + 'studies')['response'].json()
```

**Comment by Alanocallaghan** [comment]
If I include that, I simply get an empty array, because the response field is empty.

**Comment by eweitz** [comment]
I see, and can reproduce your issue by using a different `gcloud` profile.

As you found, the `/studies` endpoint does indeed only return studies that are editable by the current user.  Architecturally, https://portals.broadinstitute.org/single_cell/api/v1/studies maps to https://portals.broadinstitute.org/single_cell/studies.  Per your comments it, you'd see 0 studies in the latter, thus your empty array in the former.

Being able to extract public study metadata is a reasonable use case.  Unfortunately there's no way to get the data you seek with the current API, but your input here will help guide future API design.

If you need this data for a publication, please let us know.  Otherwise, I'll let you know when the API supports your use case!

**Comment by emattei** [comment]
Hi,
I was wondering if the API now support this functionality.
I this this is a major issue. More of the APIs requires a {id} or {study_id} that can be obtain only through /studies API.
Is there a workaround to get those ids?

Thank you!

**Comment by eweitz** [comment]
Hi @emattei, we're working on functionality that will enable this, and will update here when it is ready to use.

**Comment by jlchang** [comment]
Hi @emattei and @Alanocallaghan,

You can obtain information on public studies in addition to studies editable by your user with the /site/studies API endpoint. Endpoints under /site use the Study accession and won't need an {id} or {study id}.

From /site/studies you can obtain gene and cell counts. The portal doesn't currently explicitly collect author information but you might be able to extract authors from the study description? I'll add a ticket to our backlog regarding the inclusion of study creation/update dates.

Hope the additional API endpoint options will address your needs. Please reach out if you have question or feedback.

Regards,

Jean
