### ISSUE TITLE
Human cell atlas data portal?

### ISSUE THREAD

**Issue by Bohdan-Khomtchouk** [broadinstitute/single_cell_portal#56]
Hi!  Any plans/cross-talk between Single Cell Portal and https://prod.data.humancellatlas.org?

**Comment by jlchang** [comment]
Hi Bohdan,

Great question! Yes, we do have plans to support working with data from the Human Cell Atlas Data Portal in Single Cell Portal. Our product owner is unavailable this week but I'll ask her to respond more specifically to your inquiry early next week.

Regards,

Jean

**Comment by vickylihorst** [comment]
Hi @Bohdan-Khomtchouk, what features and/or datasets are you looking at for this integration?

**Comment by Bohdan-Khomtchouk** [comment]
@vickylihorst Nothing immediate at this moment, just trying to get a better sense of the single-cell ecosystem and its interoperability.  For instance, https://github.com/Bioconductor/HCABrowser is another one on the radar.  Very excited about the cool work you're doing!

**Comment by Bohdan-Khomtchouk** [comment]
@vickylihorst perhaps of interest: https://docs.google.com/document/d/1xjUWJ5-WLFyuAmDPQrHNIzD_gkD4IVxquwZlJrdFCG8/edit#heading=h.lf71cq751o94
