### ISSUE TITLE
studies missing from previous portal

### ISSUE THREAD

**Issue by sandrine-muller-research** [broadinstitute/single_cell_portal#59]
Hello,

I downloaded a few months ago a single cell dataset from the previous version of the portal (10x ASD in the cortex, downloaded with my Broad account). I wanted to check again the references of this dataset but could not find it anymore. Any idea why it has disappeared from the portal? 

Thank you very much!

Best

Sandrine

**Comment by vickylihorst** [comment]
Hi Sandrine,

Thank you for using the portal. The study owners control the studies, including whether the study is public vs private, and what study files are available.

For your issue, are you able to see the study at all? If you used to be able to visit the URL of the study, but not anymore, it's likely that the study owner either deleted the study or made it private. Do you happen to know the study owner(s)? If you are still able to view the study page, I'd suggest contacting the study owners to inquire about the data files.

Best,
Vicky

**Comment by sandrine-muller-research** [comment]
Hi Vicky,

Thank you so much for your quick answer!
I am not able to see the study page anymore.
Luckily, I copy paste the information provided on the portal when I
downloaded the dataset. Here are the info (I do not know however if the
first author of the publication is the study owner):

By Velmeshev et al, 2018, submitted. We aimed to gain insight into the
molecular pathology of specific neuronal and glial subtypes by analyzing
single cells in the cortex of ASD patients. To this end, we performed
unbiased nuclei isolation and snRNA-seq from 21 post-mortem tissue samples
from the prefrontal (PFC), anterior cingulate (ACC) and insular (IC)
cortical regions of seven patients with ASD and eight control subjects
followed by high-throughput single-nucleus RNA sequencing. We identified 11
neuronal and seven glial cell types; these included known subtypes of
excitatory neurons and interneurons, two neuronal clusters highly enriched
in the regions of the cortex in the limbic system, main types of glial
cells and brain endothelial cells. To identify genes dysregulated in ASD in
a cell type-specific manner, we compared nuclei profiles from ASD samples
and control subjects. In total, we identified 1,797 differentially
expressed genes (DGEs); 1,118 (62%) of these genes were differentially
expressed in a single cell type. Our findings show that synaptic signaling
of upper-layer excitatory neurons is especially affected in ASD. Moreover,
we find significant dysregulation of grey matter astrocyte-encoded genes
responsible for glutamate uptake and modulation of synaptic plasticity.
These findings indicate molecular pathological changes in upper-layer
cortical neuron circuits and aberrant astroglia-neuronal interactions in
ASD and identify potential cellular and molecular therapeutic targets.

Do you think you can retrieve more infomation about this dataset/project?
(other collaborators? has the project become provate?)
It could help me write to the first author.

Thank you very much

Best

Sandrine

**Comment by vickylihorst** [comment]
Hi Sandrine,

Due to our privacy policy, I can not disclose such information. This is also to protect our users like you who have the full right to control their studies.
