### ISSUE TITLE
Email sent to everyone when sharing a project

### ISSUE THREAD

**Issue by gaelcge** [broadinstitute/single_cell_portal#62]
Hi guys
Every time I am adding someone's email address to access a private study (share onglet), people whom already has access to the study will be notified by email than someone new has been added. Is it possible to turn off the notification?
Thanks a lot for the work you are doing!!!

**Comment by vickylihorst** [comment]
Hi @gaelcge, thanks for using the portal! Currently, users can configuration their notification settings, however as a study owner, one can't configure notification settings for all collaborators in the study. I'd be happy to explore your use case though in the next couple of quarters; I'll add it to our backlog!
