### ISSUE TITLE
Uploading multiple fastqs

### ISSUE THREAD

**Issue by allonw** [broadinstitute/single_cell_portal#7]
It seems that the system allows uploading individual .fastq.gz files, but not tar files of multiple fastqs. It also doesn't allow uploading selecting multiple files for upload.

Can you please allow .tar.gz? It's impractical otherwise for studies with thousands of cells.

**Comment by TimothyTickle** [comment]
Hey Allon :-),

The portal allows both fastq.gz and .fastq.tar.gz (and example of a study with a tar https://portals.broadinstitute.org/single_cell/study/th17-pathogenicity ). What is the size tar you are attempting to upload and does it have the extension ".fastq.tar.gz".

Cordially,

Tim

**Comment by allonw** [comment]
Hi :)

Oh, I didn't realize it must end in ".fastq.tar.gz" and not just ".tar.gz" (maybe better to note it on the relevant tab for step 6?)

I'm trying to upload a 61GB file. Once I renamed it according to the above, I am able to start the upload, but it's very slow, and after >24h I got a "bad gateway" error message.

PS. as a future enhancement, I think that a ssh command line interface will be very useful for raw-data file uploads

**Comment by TimothyTickle** [comment]
Hello Allon,

We have been able to load archives of this size. I will email you offline to access the data and try on my end. The current file upload is only an intermediary process for a more "Big data" solution for file upload that will arrive in the future.

Cordially,

Tim
