### ISSUE TITLE
How to handle mtx files in R

### ISSUE THREAD

**Issue by kvittingseerup** [broadinstitute/single_cell_portal#72]
Hi SingleCellPortal

I've been looking with great interest at some of your data stored in the mtx format - which as far as I can tell is a convenient way to store sparse matrixes.

So these typically have 3 column. What are in the columns when the data is single cell expression? It would be nice to create a small README for studies using these files.

Along with the MATLAB, Python and C code for handling the data [here](https://math.nist.gov/MatrixMarket/formats.html#coord) I was wondering if you could you provide a script for getting the data into R (which also supports sparse matrixes)?

Cheers
Kristoffer

**Comment by jlchang** [comment]
Hi Kristoffer,

A version of the mtx format is standard output for data processed by 10x Genomics' CellRanger program, which they refer to as [MEX](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/output/matrices). Their [detailed description] (https://kb.10xgenomics.com/hc/en-us/articles/115000794686-How-is-the-MEX-format-used-for-the-gene-barcode-matrices-) of their file format may also be useful to you.

10x provides an R library, cellrangerRkit, to work with their data.
10x also lists several resources for [Secondary Analysis in R](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/rkit), including [Seurat](https://satijalab.org/seurat/vignettes.html) 

Regards,

Jean

**Comment by jlchang** [comment]
Hi Kristoffer,

Closing this ticket on the assumption that the information provided was sufficient for your needs. Please feel free to reach out to us if you have additional questions.

Regards,

Jean

**Comment by kvittingseerup** [comment]
It was all the info I needed thanks.  I just want to add that according the [10X website ](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/rkit)to the 10X R package rkit:

> due to the growth of third-party tools that provide similar capabilities, this package has been deprecated and it is unable to analyze data produced by the Cell Ranger 3.0 software

**Comment by kvittingseerup** [comment]
Well actually as I try importing the data I run into more problems:
1) Which version of CellRanger are you using (makes a difference if it is before and after 3.0.0).
2) Next time you update the pipeline you could make it easier to use e.g. seurat by output multiple experiments to multiple folders with standard names (as Seurat looks for the standard names).

**Comment by jlchang** [comment]
Hi Kristoffer,

The majority of study files currently in Single Cell Portal are uploaded by the study owners so data organization is up to the discretion of the study owner. It may be that the files from the study you are exploring were generated using tools other than CellRanger->Seurat.

Currently our file ingest process accepts genes.tsv.gz but not features.tsv.gz therefore the available  files should be before CellRanger version 3.0.0

Regards,

Jean
