### ISSUE TITLE
No gene gene expression in the tSNE

### ISSUE THREAD

**Issue by kvshams** [broadinstitute/single_cell_portal#73]
Hi,
I am not able to get the gene expression in the tSNE on single cell portal (Accession SCP491). It shows `This study has no gene expression and clustering data available`.

**Comment by bistline** [comment]
kvshams -

I'm looking into this issue right now - I'll let you know if I find anything.

Best,

Jon
Single Cell Portal Team

**Comment by bistline** [comment]
In looking at the logs, I see that the file uploaded fine and the parse ran without error, however no genes were extracted.  I tried downloading the file to inspect it, and I noticed something: the gzipped version of the file has an issue where the first line doesn't terminate with a newline, and when you try to read the second line, you get an EOF error, which the parser interprets as the end of the file.  The uncompressed version is fine - that I can read line by line without any issue.  I tried recompressing the file with gzip, and when I tried to read it line by line in the terminal, it worked as intended.  So as far as I can tell, there's an issue with the line endings in the compressed archive, but not the original source file.  I also tested with some other gzipped data, and they all read correctly, so it appears to just be in the uploaded version of that file.

The quickest workaround would be to delete the compressed matrix from the portal and then upload the uncompressed version and parse that.  I'm not sure why the line endings aren't correct in that original file (zcat shows that there are ~12K lines, but the Ruby parser only sees the first line).

Please let me know if there's anything else we can assist with.

Best,

Jon

**Comment by kvshams** [comment]
It worked...! I uploaded the unzipped file.
Thanks a lot!
