### ISSUE TITLE
T Helper Cell Cytokines Modulate Intestinal Stem Cell Renewal and Differentiation resource not available

### ISSUE THREAD

**Issue by TomasBrabec** [broadinstitute/single_cell_portal#82]
I have been facing this issue for some time now. Data deposited here from study: "T Helper Cell Cytokines Modulate Intestinal Stem Cell Renewal and Differentiation" is no longer available, although it was at first. Whenever I try to connect to this data-set, it shows "Page not found".

if it would be possible to resolve this issue, it would be great!

Thanks,
Tomas

**Comment by jlchang** [comment]
@TomasBrabec,

Searching Single Cell Portal for "T Helper Cell Cytokines Modulate Intestinal Stem Cell Renewal and Differentiation", I found this study: https://singlecell.broadinstitute.org/single_cell/study/SCP241
The Single Cell Portal URL was updated in September, old URLs should be directed to the new URL. Could you please send us the URL for the "Page not found" issue you experienced? We'll see if a faulty redirect might have caused the availability problem.

Note that data is only available for download from public studies when you are logged into the Portal. Please sign in before accessing the study at its new URL and let us know if this resolves the data access issue.

Regards,

Jean

**Comment by TomasBrabec** [comment]
Dear Jean,

thank you for the feedback. The link you  posted works perfectly. The only issue is that the old one published in the paper no longer works...

Best,
Tomas
