### ISSUE TITLE
Single-cell RNA-seq reveals new types of human blood dendritic cells, monocytes, and progenitors

### ISSUE THREAD

**Issue by Diana-star-code** [broadinstitute/single_cell_portal#87]
Hello, I am trying to open the EXPLORE option in single cell portal for the following publication **Single-cell RNA-seq reveals new types of human blood dendritic cells, monocytes, and progenitors**.
But it is stuck. 
Can this be fixed?

**Comment by jlchang** [comment]
@Diana-star-code,
The study may be stuck due to a recently discovered rendering bug. I believe a bugfix is in progress. I hope to have an update for you later today.

Regards,

Jean

**Comment by Diana-star-code** [comment]
Thank you very much. Will wait for your update.

**Comment by jlchang** [comment]
@Diana-star-code,

We plan to deploy a bugfix today to address the issue. To confirm, is the study you are looking to EXPLORE:
https://singlecell.broadinstitute.org/single_cell/study/SCP43

I'll let you know when the bugfix has been put into production.

Regards,

Jean

**Comment by jlchang** [comment]
@Diana-star-code 

We have deployed a bugfix for the issue you reported. Please let us know if the issue is resolved for you.

Regards,

Jean

**Comment by jlchang** [comment]
@Diana-star-code,

Checking in to see if you are now able to EXPLORE your studies of interest? Scatter plots are visible on my end and I am assuming the issue is resolved. Please reach out to us if you are still experiencing difficulties.

Best regards,

Jean

**Comment by Diana-star-code** [comment]
Hi Jean
Sorry I didnt answer before. Yes, I can now explore the study in the
portal.
Thank you very much for your help!

Diana
