### ISSUE TITLE
Reference for scRNA-Seq data on Single Cell Portal

### ISSUE THREAD

**Issue by mmadeira97** [broadinstitute/single_cell_portal#89]
For the following data set, I cannot find the journal article or anything to go along with it:

"Study: Single cell RNA-seq of adult and pediatric glioblastoma."

**Comment by eweitz** [comment]
Hi @mmadeira97,

That particular study -- [SCP393](https://singlecell.broadinstitute.org/single_cell/study/SCP393) -- does not seem to have a journal article associated with it.  Single Cell Portal does not require studies to have published articles, so it is a valid study.  You may want to check again in the future in case this SCP study gets updated.

That said, you can download data for this study if you sign into the portal.

Let us know of any other questions!

Best,
Eric

Single Cell Portal team
