### ISSUE TITLE
Cancel upload does not delete partially uploaded file [Minor-usability].

### ISSUE THREAD

**Issue by matanhofree** [broadinstitute/single_cell_portal#9]
Using the cancel upload leaves a partially uploaded file. In order to upload the file one needs to delete the partial upload first, otherwise you get a cryptic internal server error. I would suggest simply deleting partial upload on a cancel.

**Comment by TimothyTickle** [comment]
This is a good catch, we will start working on this and pull it into the next update. Thank you for the feed back.

**Comment by TimothyTickle** [comment]
This will be in out next release of code.
