### ISSUE TITLE
[General Feedback] Google authentication timing

### ISSUE THREAD

**Issue by mshadbolt** [broadinstitute/single_cell_portal#92]
Hi all

I have recently been using the Single Cell Portal quite a bit due to my work with the Human Cell Atlas project. I wanted to say that I think the portal is awesome! But my main annoyance so far has been with google authentication.

I find it a bit cumbersome to have to reauthenticate with google multiple times a day. Is there any way of granting permissions in a more permanent way? It seems at the moment it might be only a few hours before it kicks you out and you have to reauthenticate?

This is obviously a nice to have feature and doesn't block me from using the portal but wanted to give the feedback in case others also find it a bit annoying or if maybe there is a way to grant permissions permanently that I am not aware of. Or there could well be a very good reason why the permissions are not granted permanently or on a longer term basis, but wanted to leave the feedback here regardless.

**Comment by jlchang** [comment]
Hi @mshadbolt,

Thank you for your kind words about the Portal. I wanted to let you know that we feel your pain! Re-authentication is needed fairly frequently and affects our development team as well. Unfortunately this requirement is a side effect of regulatory compliance for Portal certification to be able to work with certain types of government-owned primary data.

Wish I could share more encouraging news but we're contractually obligated to deploy authentication in this way. Hope you'll continue to use the portal despite the necessary inconvenience.

Best regards,

Jean
