### ISSUE TITLE
More Intuitive Filters on Home Page

### ISSUE THREAD

**Issue by DarioS** [broadinstitute/single_cell_portal#93]
There are buttons such as Most Recent and Most Popular but I would like to see filtering by human or mouse and by the type of sample; tissue or cell line or xenograft, for example.

**Comment by eweitz** [comment]
@DarioS, more useful filters -- for species, organ, and other scientific categories -- are under heavy development and are coming soon!

We'll note here when those improved filters are generally available in Single Cell Portal.

**Comment by jlchang** [comment]
@DarioS We have introduced a new Advanced Search feature you can opt-in to try:
<img width="837" alt="Try_advanced_search" src="https://user-images.githubusercontent.com/6005195/104186884-103d4880-53e5-11eb-85e6-0873cb9e8f5e.png">

[Related documentation](https://github.com/broadinstitute/single_cell_portal/wiki/Search-Studies#faceted-search-available-under-advanced-search)

If you have the time to check out Advanced Search and have feedback for us, please let us know at scp-support@broadinstitute.zendesk.com.

**Comment by DarioS** [comment]
How about the number of biological samples per data set and being able to distinguish data sets for which the samples belong to classes (e.g. treatment responder versus resistant) from those which do not have any classes? I am hoping to easily identify data sets which are suitable for cross-validated classification.

**Comment by eweitz** [comment]
Hi @DarioS, thanks for following up with that thoughtful proposal!  Could you email your feature request to scp-support@broadinstitute.zendesk.com?  Someone from the team will follow up with you over there.
