### ISSUE TITLE
Read Count Data

### ISSUE THREAD

**Issue by vschulz** [broadinstitute/single_cell_portal#94]
It would be hugely helpful for studies to include read count data.  This would allow easy reprocessing using different analysis methods.  The normalized processed expression matrices are helpful for some things, but are very limited for analysis.  Fastq files, when available, are an option, but it is much more difficult to reprocess those rather than having a relatively small, easy to use read count table

**Comment by devonbush** [comment]
Hi, thanks for that suggestion.  Including read count data, protocols, units, and other data that would allow reprocessing and reanalysis of data are currently under heavy development--we agree that those will add a lot of value to studies in the portal.  We will keep this issue updated as we release those features

**Comment by danhtruong** [comment]
I also agree. Some of the studies have normalized data which are good for visualization but make it difficult to perform data correction and differential analysis.

**Comment by jlchang** [comment]
@vschulz @danhtruong Study owners can now upload raw count matrices as an SCP file type. (Previously study owners uploaded raw count files as "other"). The download tab now includes a manifest.json file which indicates the file type of all available files. For expression matrices, library preparation protocol and other expression file info is now being collected and can be found in the manifest.json file.

If you have feedback regarding the new raw counts feature, please let us know at scp-support@broadinstitute.zendesk.com.
