### ISSUE TITLE
Missing studies

### ISSUE THREAD

**Issue by liuxl18-hku** [broadinstitute/single_cell_portal#96]
Hi,

Thanks for the rocking portal! Recently I accessed the following two studies (which I think from HCA March 2020 release) using my HKU Uni account (google sponsored):

https://singlecell.broadinstitute.org/single_cell/study/SCP771/2020-mar-census-adult-immune-10x
https://singlecell.broadinstitute.org/single_cell/study/SCP766/2020-mar-profiling-adult-bonemarrow-10x

I can still find data matrix and a bunch of other info on HCA portal, however, the parts I missed  from our single cell portal are cell type curation from fields expert. May I know the two datasets are removed from our portal or just I am banned to get them because of updated data privacy policies.

bless~

**Comment by jlchang** [comment]
Hi @liuxl18-hku 

Our understanding is that those studies are in the process of being developed and validated, they were unset as public studies to prevent use before the official release (and during validation). 

The HCA DCP team is looking forward to releasing the data formally and you using the data, but data may change during validation.  It is recommended that scientists wait for this process to complete and be announced before leveraging the data. 

The HCA DCP team at data-help@humancellatlas.org is the ideal group to ask those studies, including when the studies will be publicly accessible again.

Thanks for using Single Cell Portal!

Best regards,
Jean

Single Cell Portal team

**Comment by liuxl18-hku** [comment]
@jlchang , Thank you!
