### ISSUE TITLE
Data submission problem 

### ISSUE THREAD

**Issue by yulongliu68** [broadinstitute/single_cell_portal#98]
Trying to upload data in a study on 5/21 and 5/22 multiple times, but somehow only the matrix is uploaded, both the metadata and the mapping data get deleted within 5 minutes after the upload. Also, I never received any data uploaded notification in email like I usually do. There is also no error message.  
I have double checked the files that I uploaded, there is no deviation in structure from the files that I have uploaded before.
I have also deleted the entire study and tried to remake an alternative study but still encounter the same problem. 

I have 17 other studies on the portal, this is the first that I encounter this problem. 

https://singlecell.broadinstitute.org/single_cell/study/SCP957/40dpf-ovary-follicle-theca-and-stromal
--

**Comment by bistline** [comment]
yulonglui68 -

Thank you for letting us know about your issues uploading your data to the portal.  I will look into this further.  In the meantime, can you resubmit your request to our main help desk:

scp-support@broadinstitute.zendesk.com

We are consolidating our support into a single place.  Once you have opened the ticket there, I will close this request here.

Best,

Jon
Single Cell Portal Team

**Comment by bistline** [comment]
Closing, issue was resolved in Zendesk queue.
